name: Daily Rebuild

on:
  schedule:
    - cron: '0 20 * * *'  # 6am AEST daily
  workflow_dispatch:       # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare deploy hook
        run: curl -X POST ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
